import numpy as np
import glob
import os

# 1. VERIFIED PLANCK DATA (For Comparison)
planck_l = np.array([2, 10, 30, 50, 100, 150, 215, 300, 400, 450, 540, 600, 700, 800, 850, 950, 1050, 1150, 1250, 1350, 1450, 1550, 1650, 1750, 1850, 1950])
planck_Dl = np.array([900, 850, 1100, 1550, 3400, 5100, 5750, 3800, 2100, 1850, 2600, 2250, 1550, 2400, 2500, 1850, 1250, 1100, 850, 900, 800, 500, 400, 350, 300, 250])
planck_err = np.array([300, 200, 150, 100, 80, 70, 60, 50, 40, 40, 40, 40, 40, 50, 50, 50, 50, 60, 60, 70, 70, 80, 80, 90, 90, 100])

# ... (Keep the imports and Planck data from previous script)

def calculate_chi2(file_path):
    try:
        data = np.loadtxt(file_path)
        l_sim, cl_sim = data[:, 0], data[:, 1]
        dl_sim = cl_sim * (2.7255e6)**2 
        dl_interp = np.interp(planck_l, l_sim, dl_sim)
        return np.sum(((dl_interp - planck_Dl) ** 2) / (planck_err ** 2))
    except: return float('inf')

# --- NEW SECTION: BASELINE COMPARISON ---
print("Calculating Standard ΛCDM Baseline Score...")
# Find the baseline file generated by your 'Mirror' function
baseline_file = glob.glob("output_sweep/lcdm_baseline*cl.dat")

if baseline_file:
    lcdm_score = calculate_chi2(baseline_file[0])
    print(f"📊 Standard ΛCDM Baseline χ²: {lcdm_score:.2f}")
else:
    print("⚠️ No baseline file found. Run the generator first!")
    lcdm_score = None

# --- SCANNING THE 1,000 UNIVERSES ---
files = [f for f in glob.glob("output_sweep/*cl.dat") if "lcdm" not in f]
results = []

for f in files:
    results.append((f, calculate_chi2(f)))

results.sort(key=lambda x: x[1])

print("\n🏆 LEADERBOARD vs. STANDARD MODEL 🏆")
for i in range(min(3, len(results))):
    fname, score = results[i]
    delta = score - lcdm_score if lcdm_score else 0
    status = "✅ BEATS ΛCDM!" if delta < 0 else "❌ Worse than ΛCDM"
    print(f"Rank {i+1}: {os.path.basename(fname)}")
    print(f"   Score: {score:.2f} (Δχ²: {delta:+.2f}) | {status}")

# 2. SCAN ALL 1,000 FILES
files = glob.glob("output_sweep/*cl.dat")
results = []

print(f"Analyzing {len(files)} universes for best fit...")

for f in files:
    c2 = calculate_chi2(f)
    results.append((f, c2))

# 3. RANK AND SHOW THE TOP 3
results.sort(key=lambda x: x[1])

print("\n🏆 THE LEADERBOARD: TOP 3 UNIVERSES 🏆")
for i in range(min(3, len(results))):
    filename, score = results[i]
    print(f"Rank {i+1}: {os.path.basename(filename)}")
    print(f"   Chi-Squared Score: {score:.2f} (Lower is better)")